-- MySQL Script generated by MySQL Workbench
-- Mon May 24 10:30:16 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_RedeSocial
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_RedeSocial
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_RedeSocial` DEFAULT CHARACTER SET utf8 ;
USE `db_RedeSocial` ;

-- -----------------------------------------------------
-- Table `db_RedeSocial`.`tb_usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_RedeSocial`.`tb_usuarios` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `usuario` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `usuario_UNIQUE` (`usuario` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_RedeSocial`.`tb_grupos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_RedeSocial`.`tb_grupos` (
  `id_grupo` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `tema` VARCHAR(45) NOT NULL,
  `fk_usuario_criador` INT NOT NULL,
  PRIMARY KEY (`id_grupo`),
  UNIQUE INDEX `id_grupo_UNIQUE` (`id_grupo` ASC) VISIBLE,
  INDEX `fk_tb_grupos_tb_usuarios_idx` (`fk_usuario_criador` ASC) VISIBLE,
  CONSTRAINT `fk_tb_grupos_tb_usuarios`
    FOREIGN KEY (`fk_usuario_criador`)
    REFERENCES `db_RedeSocial`.`tb_usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_RedeSocial`.`tb_postagens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_RedeSocial`.`tb_postagens` (
  `id_postagem` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(145) NULL,
  `url_imagem` VARCHAR(255) NULL,
  `fk_grupo_criador` INT NOT NULL,
  `fk_usuario_criador` INT NOT NULL,
  PRIMARY KEY (`id_postagem`),
  INDEX `fk_tb_postagens_tb_grupos1_idx` (`fk_grupo_criador` ASC) VISIBLE,
  INDEX `fk_tb_postagens_tb_usuarios1_idx` (`fk_usuario_criador` ASC) VISIBLE,
  CONSTRAINT `fk_tb_postagens_tb_grupos1`
    FOREIGN KEY (`fk_grupo_criador`)
    REFERENCES `db_RedeSocial`.`tb_grupos` (`id_grupo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_postagens_tb_usuarios1`
    FOREIGN KEY (`fk_usuario_criador`)
    REFERENCES `db_RedeSocial`.`tb_usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_RedeSocial`.`tb_inscritos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_RedeSocial`.`tb_inscritos` (
  `fk_usuario_inscrito` INT NOT NULL,
  `fk_grupo_inscrito` INT NOT NULL,
  PRIMARY KEY (`fk_usuario_inscrito`, `fk_grupo_inscrito`),
  INDEX `fk_tb_usuarios_has_tb_grupos_tb_grupos1_idx` (`fk_grupo_inscrito` ASC) VISIBLE,
  INDEX `fk_tb_usuarios_has_tb_grupos_tb_usuarios1_idx` (`fk_usuario_inscrito` ASC) VISIBLE,
  CONSTRAINT `fk_tb_usuarios_has_tb_grupos_tb_usuarios1`
    FOREIGN KEY (`fk_usuario_inscrito`)
    REFERENCES `db_RedeSocial`.`tb_usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_usuarios_has_tb_grupos_tb_grupos1`
    FOREIGN KEY (`fk_grupo_inscrito`)
    REFERENCES `db_RedeSocial`.`tb_grupos` (`id_grupo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_RedeSocial`.`tb_comentarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_RedeSocial`.`tb_comentarios` (
  `id_comentario` INT NOT NULL AUTO_INCREMENT,
  `comentario` VARCHAR(45) NOT NULL,
  `fk_postagem` INT NOT NULL,
  PRIMARY KEY (`id_comentario`),
  INDEX `fk_tb_comentarios_tb_postagens1_idx` (`fk_postagem` ASC) VISIBLE,
  CONSTRAINT `fk_tb_comentarios_tb_postagens1`
    FOREIGN KEY (`fk_postagem`)
    REFERENCES `db_RedeSocial`.`tb_postagens` (`id_postagem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
