-- MySQL Script generated by MySQL Workbench
-- Mon May 24 12:26:39 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_AskMarinho
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_AskMarinho
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_AskMarinho` DEFAULT CHARACTER SET utf8 ;
USE `db_AskMarinho` ;

-- -----------------------------------------------------
-- Table `db_AskMarinho`.`tb_usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_AskMarinho`.`tb_usuarios` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(100) NOT NULL,
  `nascimento` DATE NOT NULL,
  `genero` VARCHAR(45) NOT NULL,
  `telefone` INT NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `usuario_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_AskMarinho`.`tb_grupos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_AskMarinho`.`tb_grupos` (
  `id_grupo` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `tema` VARCHAR(45) NOT NULL,
  `fk_id_usuario` INT NOT NULL,
  PRIMARY KEY (`id_grupo`),
  UNIQUE INDEX `id_grupo_UNIQUE` (`id_grupo` ASC) VISIBLE,
  INDEX `fk_tb_grupos_tb_usuarios_idx` (`fk_id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_tb_grupos_tb_usuarios`
    FOREIGN KEY (`fk_id_usuario`)
    REFERENCES `db_AskMarinho`.`tb_usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_AskMarinho`.`tb_postagens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_AskMarinho`.`tb_postagens` (
  `id_postagem` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(255) NULL,
  `url_imagem` VARCHAR(255) NULL,
  `fk_id_grupo` INT NOT NULL,
  `fk_id_usuario` INT NOT NULL,
  PRIMARY KEY (`id_postagem`),
  INDEX `fk_tb_postagens_tb_grupos1_idx` (`fk_id_grupo` ASC) VISIBLE,
  INDEX `fk_tb_postagens_tb_usuarios1_idx` (`fk_id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_tb_postagens_tb_grupos1`
    FOREIGN KEY (`fk_id_grupo`)
    REFERENCES `db_AskMarinho`.`tb_grupos` (`id_grupo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_postagens_tb_usuarios1`
    FOREIGN KEY (`fk_id_usuario`)
    REFERENCES `db_AskMarinho`.`tb_usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
